# Generated by Django 3.1 on 2020-08-09 01:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('receipt_image', models.ImageField(upload_to='static/images')),
                ('date_saved', models.DateTimeField(default=datetime.datetime(2020, 8, 9, 1, 32, 53, 87127))),
            ],
        ),
    ]
