# Generated by Django 3.1 on 2020-08-09 01:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('RSaverBackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='date_saved',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 9, 1, 35, 13, 626069, tzinfo=utc)),
        ),
    ]
