# Generated by Django 3.1 on 2020-08-09 01:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('RSaverBackend', '0003_auto_20200809_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='date_saved',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 8, 9, 1, 41, 50, 291365, tzinfo=utc)),
        ),
    ]
